name: Setup, Test and Build Artifacts

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:fix

      - name: Test
        run: npm run test

      - name: Pacakge
        run: npm run package

      - name: Make
        run: npm run make
      - name: create artifact name
        #  USE THE GITHUB_SHA ENVIRONMENT VARIABLE TO CREATE A UNIQUE ARTIFACT NAME PER TARGET
        run: echo "version=${{ matrix.os }}-${GITHUB_SHA}" >> $GITHUB_ENV
      - name: use artifact name
        run: echo "Artifact name is $version"

      - uses: seepine/hash-files@v1
        id: get-hash
        with:
          patterns: |
            **/package-lock.json
            **/yarn.lock
            src/**/*.ts
            src/**/*.tsx
            **/*.html

      - name: Echo hash
        run: echo ${{ steps.get-hash.outputs.hash }}
