name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - uses: actions/cache@v4
        id: cache
        with:
          path: out
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json','**/yarn.lock','src/**/*.ts','src/**/*.tsx','src/assets/**/*','./*.html','./*.ts','./*.js','./*.json','./*.md','.github/workflows') }}

      - name: Cache Hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "Cache Hit, skipping steps..."

      - name: Lint
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run lint:fix

      - name: Test
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run test

      - name: Make
        # if not a push and cache miss then make again
        if: github.event_name != 'push' && steps.cache.outputs.cache-hit != 'true'
        run: npm run make

      - name: Publish
        # always publish on push
        if: github.event_name == 'push'
        run: npm run publish

      - name: Upload Artifact
        # build artifacts haven't been produced before, upload them for qa
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ hashFiles('**/package-lock.json','**/yarn.lock','src/**/*.ts','src/**/*.tsx','src/assets/**/*','./*.html','./*.ts','./*.js','./*.json','./*.md','.github/workflows') }}
          path: out
          overwrite: true
